version: 2.1

# ¡Hemos eliminado el bloque 'orbs:'! Ya no es necesario.

executors:
  python-exec:
    docker:
      - image: cimg/python:3.11

jobs:
  checkout_setup:
    executor: python-exec
    steps:
      - checkout
      - run:
          name: Create virtualenv and install deps
          command: |
            python -m venv .venv
            . .venv/bin/activate
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - persist_to_workspace:
          root: .
          paths:
            - .venv
            - .

  build:
    executor: python-exec
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Compile application
          command: |
            . .venv/bin/activate
            python -m compileall app
      - persist_to_workspace:
          root: .
          paths:
            - app

  test_and_quality:
    docker:
      - image: cimg/python:3.11
    parallelism: 2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: |
            . .venv/bin/activate
            mkdir -p TestResults
            pytest --junitxml=TestResults/pytest-results.xml
      - run:
          name: Run flake8
          command: |
            . .venv/bin/activate
            flake8 app tests --statistics --output-file=TestResults/flake8-report.txt || true
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults

  deploy:
    executor: python-exec
    steps:
      - attach_workspace:
          at: .
      
      # --- ¡LA NUEVA SOLUCIÓN! ---
      - run:
          name: "Find and remove old 'zombie' CLI"
          command: |
            # 1. Encontrar la ubicación del CLI antiguo
            OLD_CLI_PATH=$(which circleci || true)
            if [ -f "$OLD_CLI_PATH" ]; then
              echo "Found old CLI at: $OLD_CLI_PATH"
              # 2. Eliminarlo forzosamente
              sudo rm "$OLD_CLI_PATH"
              echo "Old CLI removed."
            else
              echo "No old CLI found. Proceeding."
            fi
            
      # 3. Instalar el CLI nuevo con 'curl' (sabemos que esto descarga el correcto)
      - run:
          name: Install NEW CircleCI CLI
          command: |
            curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
            echo "New CLI installed."
            
      # 4. Verificar que el NUEVO CLI está en uso
      - run:
          name: "Verify new CLI version"
          command: |
            circleci version
            
      # 5. Usar los comandos NUEVOS (que ahora deben funcionar)
      - run:
          name: Plan deploy in CircleCI
          command: |
            circleci release create --version="$CIRCLE_BUILD_NUM"
      
      # 6. Tu simulación
      - run:
          name: Deploy application (Simulated)
          command: |
            . .venv/bin/activate
            if [ ! -d /tmp/deploy ]; then mkdir -p /tmp/deploy; fi
            cp -r app /tmp/deploy/app
            echo "Deployed app to /tmp/deploy/app"
      
      # 7. Reportar ÉXITO
      - run:
          name: Update deploy to SUCCESS
          command: |
            circleci release finalize --version="$CIRCLE_BUILD_NUM" --status=SUCCESS
          when: on_success
          
      # 8. Reportar FALLO
      - run:
          name: Update deploy to FAILED
          command: |
            circleci release finalize --version="$CIRCLE_BUILD_NUM" --status=FAILED
          when: on_fail

  notify_email:
    executor: python-exec
    steps:
      - run:
          name: Send notification email
          command: |
            python - \<<'PY'
            import os, smtplib
            from email.message import EmailMessage

            smtp_server = os.getenv('SMTP_SERVER')
            smtp_port = int(os.getenv('SMTP_PORT','587'))
            smtp_user = os.getenv('SMTP_USER')
            smtp_pass = os.getenv('SMTP_PASS')
            recipients = os.getenv('EMAIL_RECIPIENTS','').split(',') if os.getenv('EMAIL_RECIPIENTS') else [os.getenv('DEFAULT_RECIENT')]
            subject = f"[CircleCI] {os.getenv('CIRCLE_PROJECT_REPONAME')} #{os.getenv('CIRCLE_BUILD_NUM')} - {os.getenv('CIRCLE_JOB')}"
            body = f"Job: {os.getenv('CIRCLE_JOB')}\nBuild: {os.getenv('CIRCLE_BUILD_NUM')}\nURL: {os.getenv('CIRCLE_BUILD_URL')}\n"
            msg = EmailMessage()
            msg['Subject'] = subject
            msg['From'] = smtp_user
            msg['To'] = ','.join([r for r in recipients if r])
            msg.set_content(body)
            if smtp_server and smtp_user and smtp_pass:
                s = smtplib.SMTP(smtp_server, smtp_port)
                s.starttls()
                s.login(smtp_user, smtp_pass)
                s.send_message(msg)
                s.quit()
                print('Email enviado')
            else:
                print('SMTP no configurado, no se envió correo')
            PY

workflows:
  ci_workflow:
    jobs:
      - checkout_setup:
          filters:
            branches:
              ignore: main
      - build:
          requires:
            - checkout_setup
          filters:
            branches:
              ignore: main
      - test_and_quality:
          requires:
            - build
          filters:
            branches:
              ignore: main
      - notify_email:
          requires:
            - test_and_quality
          filters:
            branches:
              ignore: main

  deploy_workflow:
    jobs:
      - checkout_setup:
          filters:
            branches:
              only: main
      - build:
          requires:
            - checkout_setup
          filters:
            branches:
              only: main
      - test_and_quality:
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - test_and_quality
          filters:
            branches:
              only: main
      - notify_email:
          requires:
            - deploy
          filters:
            branches:
              only: main
